services:
  flycloud-helper:
    environment:
      FLYCLOUDHELPER_CREDENTIAL_MASTER_KEY: ""
      FLYCLOUDHELPER_CREDENTIAL_MASTER_KEY_FILE: /run/secrets/flycloud_helper_credential_master_key
    secrets:
      - flycloud_helper_credential_master_key

secrets:
  flycloud_helper_credential_master_key:
    file: ./secrets/credential-master-key.txt
